server 
 { 
 	listen 9999 ; 
 	listen 443 ssl ; 
 	server_name 127.0.0.1; 
     index index.php index.html index.htm default.php default.htm default.html; 
 		root D:/wwwroot/127.0.0.1_9999/bilibili-downloader/web; 
     include D:/BtSoft/nginx/conf/vhost/extension/127.0.0.1/*.conf; 

	#START-ERROR-PAGE 
	#error_page 403 /403.html; 
	error_page 404 /404.html; 
     #error_page 502 /502.html; 
	#END-ERROR-PAGE 

     #HTTP_TO_HTTPS_START 
     #HTTP_TO_HTTPS_END 

     #LIMIT_INFO_START 
     #LIMIT_INFO_END 

     #SSL-INFO-START SSL证书配置 
		ssl_certificate    ssl/127.0.0.1/fullchain.pem; 
		ssl_certificate_key    ssl/127.0.0.1/privkey.pem; 
		ssl_protocols TLSv1 TLSv1.1 TLSv1.2; 
		ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE; 
		ssl_prefer_server_ciphers on; 
		ssl_session_cache shared:SSL:10m; 
		ssl_session_timeout 10m; 
		error_page 497  `https://;` 
		#SSL-INFO-END 

     #proxy-cache 
     location ~ /purge(/.*) { 
         proxy_cache_purge cache_one $1$is_args$args; 
     } 
     #proxy 
     include proxy/127.0.0.1/*.conf; 

     #PHP-INFO-START 
     include php/72.conf; 
     #PHP-INFO-END 

     # 让HTML文件也经过PHP处理
     location ~ \.(html|htm)$ {
         fastcgi_pass 127.0.0.1:9000;
         fastcgi_index index.php;
         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
         include fastcgi_params;
     }

     #REWRITE-START 
     include rewrite/127.0.0.1/*.conf; 
     #REWRITE-END 

     #redirect 
     include redirect/127.0.0.1/*.conf; 

     #access forbidden 
     location ~ ^/(.user.ini|.htaccess|.git|.svn|.project|LICENSE|README.md){
         return 404; 
     } 

     #ssl 
     location ~ \.well-known{
         allow all; 
     } 
	 
	#static-cache 
	include static_cache/127.0.0.1/*.conf; 

	access_log  D:/BtSoft/wwwlogs/127.0.0.1.log; 
     error_log  D:/BtSoft/wwwlogs/127.0.0.1.error.log; 
 }
