server
{
    listen 80;
    listen 443 ssl http2;
    server_name www.bilidown.cn bilidown.cn;

    index index.php;
    root /www/wwwroot/bilidown.cn;

    ssl_certificate    /www/server/panel/vhost/cert/bilidown.cn/fullchain.pem;
    ssl_certificate_key    /www/server/panel/vhost/cert/bilidown.cn/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    if ($server_port !~ 443){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }

    send_timeout 3600;
    client_max_body_size 50m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/tmp/php-cgi-74.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;

        fastcgi_connect_timeout 600;
        fastcgi_send_timeout 600;
        fastcgi_read_timeout 3600;
        fastcgi_buffer_size 64k;
        fastcgi_buffers 4 64k;
        fastcgi_busy_buffers_size 128k;

        fastcgi_hide_header X-Powered-By;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|ico)$ {
        expires 30d;
    }

    location ~ .*\.(js|css)?$ {
        expires 12h;
    }

    location ~ /\.
    {
        deny all;
    }

    access_log /www/wwwlogs/bilidown.cn.log;
    error_log /www/wwwlogs/bilidown.cn.error.log;
}
